title: "Goで作る静的解析ツール開発入門"
summary: "「Goで静的解析ツールを作ってみたいけど、何から始めればいいの？」と思ったことはありませんか？

Goは「静的解析がやりやすいように設計しよう」という背景を持って作られたプログラミング言語なので、go/astやgo/typesといった解析用の標準ライブラリがとても充実しています。

しかし、いざ作ろうと思っても「skeletonで雛形は作れたけど、その先のgo/astパッケージやgo/typesパッケージを使って自分がやりたい解析ロジックをどう書いていけばいいのか全く分からない」という壁にぶつかる方も多いと思います。

この本では、そんな「静的解析ツールを作りたいけれど、最初の一歩が踏み出せない」という方のために、ASTや型情報の基礎知識から実践的な解析ロジックの書き方まで、実際に動くサンプルコードとともに解説します。

読み終わる頃には「自分でも静的解析ツールが書けそう！」という状態になっていることを目指します。"
topics: ["go", "静的解析"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - starting
  - syntax-analysis-ast
  - syntax-analysis-scan
  - syntax-analysis-example
  - type-analysis-pkg
  - type-analysis-run
  - type-analysis-example
  - other-analyzer
  - appendix
